### ISSUE TITLE
Runners are in Idle state but jobs are queued

### ISSUE THREAD

**Issue by him229** [urcomputeringpal/actions-runner-kubernetes#6]
I was able to set it up successfully. Here's what I see on the actions page:
![image](https://user-images.githubusercontent.com/9799122/79711122-d8510c80-827b-11ea-84ad-e294c1e6feb0.png)
Here's the log from the runner container in the k8s pod:
![image](https://user-images.githubusercontent.com/9799122/79711147-ebfc7300-827b-11ea-94f3-e511dbbbe293.png)

However, the runners always stay in the "Idle" state on the actions page and never turn "Active". My action never actually runs on these runners -- any idea why?

![image](https://user-images.githubusercontent.com/9799122/79711201-10584f80-827c-11ea-8b41-146261936c45.png)

**Comment by jnewland** [comment]
This looks like a case where an update had been released upstream and the auto-update behavior was causing actions to be dropped, which should be fixed by #10 in the latest release. Please give it a shot and re-open if it doesn't work!
